### ISSUE TITLE
 No credentials were supplied, or the credentials were unavailable or inaccessible. No Kerberos credentials available

### ISSUE THREAD

**Issue by openPablo** [ozzi-/check_mailbox#8]
Hello. I'm getting the following error when trying to use check_mailbox.  
	
Protocol imaps not supported or disabled in libcurl
CRITICAL: MAILBOX LIST failed with return code '1' = 'UNSUPPORTED PROTOCOL' in 12 ms | runtime=12ms;90;100;0;100 messagecount=0;100000000;100000000;0;100000000

**Comment by ozzi-** [comment]
hi @openPablo 
sorry, I never saw your issue. is this still a current thing? can you give me the URL to the server in question?
